import { Issue } from '../types';

export function copyToClipboard(text: string): Promise<boolean> {
  if (navigator.clipboard && window.isSecureContext) {
    return navigator.clipboard
      .writeText(text)
      .then(() => true)
      .catch(() => fallbackCopy(text));
  } else {
    return Promise.resolve(fallbackCopy(text));
  }
}

function fallbackCopy(text: string): boolean {
  try {
    const textArea = document.createElement('textarea');
    textArea.value = text;
    textArea.style.position = 'fixed';
    textArea.style.left = '-999999px';
    textArea.style.top = '-999999px';
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();
    const successful = document.execCommand('copy');
    document.body.removeChild(textArea);
    return successful;
  } catch (err) {
    console.error('Fallback copy failed', err);
    return false;
  }
}

export function printComplaintLetter(issue: Issue, letterText: string) {
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;

  const content = `
    <!DOCTYPE html>
    <html>
      <head>
        <title>Official Municipal Complaint - ${issue.id}</title>
        <style>
          body {
            font-family: Arial, sans-serif;
            margin: 40px;
            color: #1a202c;
            line-height: 1.6;
          }
          .header {
            border-bottom: 2px solid #2b6cb0;
            padding-bottom: 12px;
            margin-bottom: 24px;
            display: flex;
            justify-content: space-between;
            align-items: center;
          }
          .title {
            font-size: 20px;
            font-weight: bold;
            color: #2b6cb0;
            margin: 0;
          }
          .badge {
            font-size: 12px;
            background: #edf2f7;
            padding: 4px 8px;
            border-radius: 4px;
            font-weight: bold;
          }
          .meta-box {
            background: #f7fafc;
            border: 1px solid #e2e8f0;
            padding: 12px;
            margin-bottom: 24px;
            border-radius: 6px;
            font-size: 13px;
          }
          .letter-body {
            white-space: pre-wrap;
            font-size: 14px;
          }
          .footer {
            margin-top: 40px;
            border-top: 1px solid #e2e8f0;
            padding-top: 12px;
            font-size: 11px;
            color: #718096;
            text-align: center;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <div>
            <h1 class="title">OFFICIAL MUNICIPAL COMPLAINT REPORT</h1>
            <div>Community Problem Reporter AI</div>
          </div>
          <div class="badge">REF: ${issue.id}</div>
        </div>

        <div class="meta-box">
          <strong>Category:</strong> ${issue.category} |
          <strong>Priority:</strong> ${issue.priority} |
          <strong>Location:</strong> ${issue.location} |
          <strong>Date Reported:</strong> ${issue.date}
        </div>

        <div class="letter-body">${escapeHtml(letterText)}</div>

        <div class="footer">
          Generated via Community Problem Reporter AI — Citizen Civic Portal | Empowering Citizens to Track & Resolve Issues
        </div>

        <script>
          window.onload = function() {
            window.print();
          };
        </script>
      </body>
    </html>
  `;

  printWindow.document.write(content);
  printWindow.document.close();
}

export function downloadAsPDF(issue: Issue, letterText: string) {
  // Uses browser print-to-pdf pipeline or formatted html blob
  printComplaintLetter(issue, letterText);
}

export function downloadAsDocx(issue: Issue, letterText: string) {
  const content = `OFFICIAL MUNICIPAL COMPLAINT REPORT
==================================================
Reference ID: ${issue.id}
Date: ${issue.date}
Category: ${issue.category}
Priority: ${issue.priority}
Location: ${issue.location}
==================================================

${letterText}

--------------------------------------------------
Generated by Community Problem Reporter AI
  `;

  const blob = new Blob([content], { type: 'application/msword;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `Municipal_Complaint_${issue.id}.doc`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}
